# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:

  pollapp-db:
    build:
      context: .
      dockerfile: Dockerfile-multiple-db
    restart: always
    volumes:
        - ../postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_MULTIPLE_DATABASES=polldb,authdb
        - POSTGRES_USER=poll
        - POSTGRES_PASSWORD=poll

    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - post-db:/var/lib/postgresql/data
volumes:
  post-db:

